apiVersion: v1
kind: Service
metadata: 
  name: myservice
  namespace: test

spec: 
  type: ClusterIP            # default service type
  ports:
    - protocol: TCP          # 
      name: http 
      port: 80  
      targetPort: app-port  # reference from pods port
   
    - protocol: TCP          # 
      name: https 
      port: 8088  
      targetPort: app-port  # reference from pods port
