apiVersion: apps/v1
kind: Deployment 
metadata:
  name: myfirstDeployment
  namespace: my-test
  labels:
    app: no-app
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test               # matchLabels should match to pod label to integrate
  template:                   # pod template start
    metadata:
      env: test               # matchLabels should match to pod label to integrate
    spec:
      containers:
         - name: nginx
           imgage: nginx:1.14.2
           resources:         # inside containers
            limits:
              memory: 2Gi
              cpu: 2
            request:
              memory: 2Gi
              cpu: 2      
          