apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: appd-release-notes-hpa
spec:
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60