apiVersion: v1
kind: PersistentVolumeClaims
metadata:
  name: nginx-pvc
  label: demo
  env: test

spec: 
  accessModes: 
    - ReadAndWriteOnce
  resources:
    request : 
      strorage: 1Gi

      

